---
# Docker compose
volumes:
  kraft_data:
services:
  init:
    image: busybox
    volumes:
      - kraft_data:/data
    user: 0:0
    command: chown -R 1000:1000 /data

  broker:
    image: apache/kafka:3.7.0
    depends_on:
      init:
        condition: service_completed_successfully
    hostname: broker
    container_name: broker
    volumes:
       - kraft_data:/data
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/data'

  gateway:
    image: conduktor/conduktor-gateway:3.0.0
    hostname: gateway
    container_name: gateway
    environment:
      KAFKA_BOOTSTRAP_SERVERS: broker:19092
      GATEWAY_ADVERTISED_HOST: localhost
      GATEWAY_SECURITY_PROTOCOL: SASL_PLAINTEXT
      GATEWAY_FEATURE_FLAGS_ANALYTICS: false
      GATEWAY_ADMIN_API_USERS: '[{username: admin, password: conduktor, admin: true}, {username: readonly, password: conduktor, admin: false}]'
      GATEWAY_PORT_START: 6969
      GATEWAY_PORT_COUNT: 1

      LOG4J2_IO_CONDUKTOR_LEVEL: debug
      LOG4J2_IO_CONDUKTOR_PROXY_AUTHORIZATION_LEVEL: debug
      LOG4J2_IO_CONDUKTOR_PROXY_REBUILDER_COMPONENTS_LEVEL: info
      LOG4J2_IO_CONDUKTOR_PROXY_NETWORK_LEVEL: info

      # TO ADD FOR 3.x
      GATEWAY_AUDIT_LOG_TOPIC: _cdk_auditLogs
      GATEWAY_ACLS_TOPIC: _cdk_acls
      GATEWAY_ENCRYPTION_CONFIGS_TOPIC: _cdk_encryptionConfig
      GATEWAY_CONSUMER_OFFSETS_TOPIC: _cdk_offsetStore
      GATEWAY_CONSUMER_SUBSCRIPTIONS_TOPIC: _cdk_consumerGroupSubscriptionBackingTopic
      GATEWAY_USER_MAPPINGS_TOPIC: _cdk_userMapping
      GATEWAY_LICENSE_TOPIC: _cdk_license
      GATEWAY_TOPIC_MAPPINGS_TOPIC: _cdk_topicMappings
      GATEWAY_INTERCEPTOR_CONFIGS_TOPIC: _cdk_interceptorConfigs
      # END OF

    depends_on:
      broker:
        condition: service_started
    ports:
      - 6969:6969
      - 8888:8888
    healthcheck:
      test: curl --fail localhost:8888/health
      interval: 10s
      retries: 4
      start_period: 5s

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      broker:
        condition: service_started
    ports:
      - "8081/tcp"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:19092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
