Description: Pipeline to release Lambda layers publicly when new release is created
Metadata:
  Author: https://github.com/johnpreston
Parameters:
  RepositoryOrganization:
    Type: String
  RepositoryProvider:
    Type: String
    AllowedValues:
      - GitHub
      - CodeCommit
    Default: GitHub
  RepositoryName:
    Type: String
  BuildLogsRetentionDays:
    Type: Number
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Default: 14
  ReferenceBranchName:
    Type: String
    Default: main
  DockerBuildspecFile:
    Type: String
    Default: .cicd/buildspec_manifest.yml
  LayersBuildSpecFile:
    Type: String
    Default: .cicd/buildspec_layers.yml
  PublicFilesBucket:
    Type: String
  ArtifactsBucket:
    Type: String
Mappings:
  RepoUrlPrefixes:
    GitHub:
      Prefix: https://github.com/
Conditions:
  UseGitHub:
    Fn::Equals:
      - Ref: RepositoryProvider
      - GitHub
  UseCodeCommit:
    Fn::Equals:
      - Ref: RepositoryProvider
      - CodeCommit
Resources:
  BuildLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: codebuild/pr-builds/${RepositoryName}
      RetentionInDays:
        Ref: BuildLogsRetentionDays
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/ResourceGroupsandTagEditorReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - Fn::Sub: codebuild.${AWS::URLSuffix}
      Policies:
        - PolicyName: ContentAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3ObjectsAccess
                Effect: Allow
                Action:
                  - s3:PutObject*
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:s3:::${PublicFilesBucket}/*
                  - Fn::Sub: arn:${AWS::Partition}:s3:::${ArtifactsBucket}/*
              - Sid: S3BucketsAccess
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:s3:::${PublicFilesBucket}
                  - Fn::Sub: arn:${AWS::Partition}:s3:::${ArtifactsBucket}
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - Fn::Sub: ${BuildLogsGroup.Arn}
              - Sid: CodeBuildReportsAccess
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*
                Action:
                  - codebuild:UpdateReportGroup
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPut*
              - Sid: CodeBuildBatch
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:*
                Action:
                  - codebuild:StartBuild
                  - codebuild:RetryBuild
              - Sid: ECRAuthAndGetFromAny
                Effect: Allow
                Resource:
                  - '*'
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
              - Sid: ECRPublishToAnyPrivateRepo
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*
                Action:
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
              - Sid: PublicEcrAuth
                Effect: Allow
                Resource:
                  - '*'
                Action:
                  - ecr-public:GetAuthorizationToken
                  - sts:GetServiceBearerToken
                  - ecr-public:BatchCheckLayerAvailability
                  - ecr-public:GetRepositoryPolicy
                  - ecr-public:DescribeRepositories
                  - ecr-public:DescribeRegistries
                  - ecr-public:DescribeImages
                  - ecr-public:DescribeImageTags
                  - ecr-public:GetRepositoryCatalogData
                  - ecr-public:GetRegistryCatalogData
              - Sid: PublicEcrPublish
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:ecr-public::${AWS::AccountId}:repository/*
                Action:
                  - ecr-public:InitiateLayerUpload
                  - ecr-public:UploadLayerPart
                  - ecr-public:CompleteLayerUpload
                  - ecr-public:PutImage

  DockerImagesBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: "${RepositoryName}-docker-build"
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole
          - Arn
      Description:
        Fn::Sub: Publishes blog on updates
      LogsConfig:
        CloudWatchLogs:
          GroupName:
            Ref: BuildLogsGroup
          Status: ENABLED
          StreamName: docker-builds
      BadgeEnabled: true
      Artifacts:
        Type: NO_ARTIFACTS
      BuildBatchConfig:
        CombineArtifacts: false
        Restrictions:
          ComputeTypesAllowed:
            - BUILD_GENERAL1_SMALL
            - BUILD_GENERAL1_MEDIUM
            - BUILD_GENERAL1_LARGE
          MaximumBuildsAllowed: 10
        ServiceRole:
          Fn::GetAtt:
            - CodeBuildRole
            - Arn
        TimeoutInMins: 60
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: PUBLIC_FILES_BUCKET
            Type: PLAINTEXT
            Value:
              Ref: PublicFilesBucket
      Source:
        Type: GITHUB
        ReportBuildStatus: true
        Location:
          Fn::If:
            - UseGitHub
            - Fn::Sub: https://github.com/${RepositoryOrganization}/${RepositoryName}
            - Fn::Sub: https://codecommit.${AWS::Region}.${AWS::URLSuffix}
        InsecureSsl: false
        BuildSpec:
          Ref: DockerBuildspecFile
      Triggers:
        Webhook: true
        BuildType: BUILD_BATCH
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_MERGED
              ExcludeMatchedPattern: false
            - Type: HEAD_REF
              Pattern: ^refs/heads/.*$
              ExcludeMatchedPattern: false
            - Type: BASE_REF
              Pattern:
                Fn::Sub: ^refs/heads/${ReferenceBranchName}$
              ExcludeMatchedPattern: false
          - - Type: EVENT
              Pattern: PUSH
              ExcludeMatchedPattern: false
            - Type: HEAD_REF
              Pattern:
                Fn::Sub: ^refs/tags/v.*$
              ExcludeMatchedPattern: false
